version: "3.3"
services:
  influxdb:
    ports:
      - "8086:8086"
    volumes:
      - "/home/nial/containers/influxdb:/var/lib/influxdb"
    image: "influxdb:1.8"
    container_name: influxdb
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - /home/nial/containers/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  heimdall:
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "81:80"
      - "445:443"
    volumes:
      - "/home/nial/containers/heimdall:/config"
    restart: unless-stopped
    image: "lscr.io/linuxserver/heimdall:latest"
  grafana:
    user: "0"
    container_name: grafana
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - "3000:3000"
    volumes:
      - "/home/nial/containers/grafana:/var/lib/grafana"
    restart: unless-stopped
    image: "grafana/grafana:latest"

  pihole-exporter:
    container_name: pihole-exporter
    environment:
      - PIHOLE_HOSTNAME=100.113.75.58
      - PIHOLE_PASSWORD=
      - PORT=9617
    ports:
      - 9617:9617
    image: ekofr/pihole-exporter:latest

  sabnzbd-exporter:
    container_name: sabnzbd-exporter
    environment:
      - SABNZBD_BASEURL=http://100.125.70.69:8082/sabnzbd/
      - SABNZBD_APIKEY=c464f4dee3b64587ba22d0efd8849fdd
    ports:
      - 9387:9387
    restart: always
    image: msroest/sabnzbd_exporter

  portainer_agent:
    ports:
      - 9001:9001
    container_name: portainer_agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    image: portainer/agent:latest

  cribl:
    hostname: pi4
    privileged: true
    environment:
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@newnewtitanium:4200?group=default_fleet&tag=pi4
      - CRIBL_DIST_MODE=managed-edge
      - CRIBL_EDGE=1
    ports:
      - 9420:9420
    volumes:
      - /:/hostfs:ro
    restart: unless-stopped
    container_name: cribl-edge
    image: cribl/cribl:latest

volumes:
  prometheus_data:
