services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/nial/homelab/pi4/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/nial/homelab/pi4/caddy/data:/data
      - /home/nial/homelab/pi4/caddy/config:/config
      #- $CONFIGDIR/caddy/cert:/cert
      - /var/lib/tailscale/certs/pi4.tailnet-ea75.ts.net.crt:/cert/tailscale.crt:ro
      - /var/lib/tailscale/certs/pi4.tailnet-ea75.ts.net.key:/cert/tailscale.key:ro
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: