version: '3.3'
services:
    influxdb:
        ports:
            - '8086:8086'
        volumes:
            - '/home/nial/influxdb:/var/lib/influxdb'
        image: 'influxdb:1.8'
        container_name: influxdb
        restart: unless-stopped
    speedtest-to-influxdb:
        container_name: speedflux
        environment:
            - NAMESPACE=None
            - INFLUX_DB_ADDRESS=100.88.213.67
            - INFLUX_DB_PORT=8086
            - INFLUX_DB_USER=root
            - INFLUX_DB_PASSWORD=ad
            - INFLUX_DB_DATABASE=speedtest
            - SPEEDTEST_INTERVAL=5
            - SPEEDTEST_FAIL_INTERVAL=5
            - INFLUX_DB_TAGS=*
            - LOG_TYPE=info
        image: dontobi/speedflux.rpi
        restart: unless-stopped
    netdata:
        image: netdata/netdata
        container_name: netdata
        pid: host
        network_mode: host
        restart: unless-stopped
        cap_add:
            - SYS_PTRACE
            - SYS_ADMIN
        security_opt:
            - apparmor:unconfined
        volumes:
            - netdataconfig:/etc/netdata
            - netdatalib:/var/lib/netdata
            - netdatacache:/var/cache/netdata
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    netdataconfig:
    netdatalib:
    netdatacache: