version: "3"
services:
  grafana:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    container_name: grafana
    entrypoint:
      - /run.sh
    environment:
      - PATH=/usr/share/grafana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    hostname: 7d47b8d6cb45
    image: grafana/grafana:latest
    ipc: private
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:05
    ports:
      - 3000:3000/tcp
    stdin_open: true
    tty: true
    user: 472
    working_dir: /usr/share/grafana
  homebridge:
    container_name: homebridge
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/homebridge/node_modules/.bin
      - QEMU_ARCH=aarch64
      - S6_KEEP_ENV=1
      - NODE_VERSION=14.17.3
      - HOMEBRIDGE_VERSION=1.3.4
      - CONFIG_UI_VERSION=4.41.1
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - ENABLE_AVAHI=1
    hostname: odroid
    image: oznu/homebridge:ubuntu
    ipc: private
    logging:
      driver: json-file
      options: {}
    networks:
      - host
    volumes:
      - /home/nial/homebridge:/homebridge
    working_dir: /homebridge
  librespeed:
    container_name: librespeed
    entrypoint:
      - /init
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=false
      - DB_TYPE=sqlite
      - DB_NAME=DB_NAME
      - DB_HOSTNAME=DB_HOSTNAME
      - DB_USERNAME=DB_USERNAME
      - DB_PASSWORD=DB_PASSWORD
      - DB_PORT=DB_PORT
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - 'PS1=$(whoami)@$(hostname):$(pwd)\$ '
      - HOME=/root
      - TERM=xterm
    hostname: 3c8f0c5707dc
    image: ghcr.io/linuxserver/librespeed
    ipc: shareable
    labels:
      build_version: 'Linuxserver.io version:- 5.2.4-ls64 Build-date:- 2021-07-06T01:04:29-04:00'
      com.docker.compose.config-hash: a94e827b734adf03404ea0cdc9ab9299eb8a5f56b0951999397bd575388751a0
      com.docker.compose.container-number: 1
      com.docker.compose.oneoff: False
      com.docker.compose.project: nial
      com.docker.compose.project.config_files: docker-compose.yml
      com.docker.compose.project.working_dir: /home/nial
      com.docker.compose.service: librespeed
      com.docker.compose.version: 1.25.0
      maintainer: aptalca
      org.opencontainers.image.authors: linuxserver.io
      org.opencontainers.image.created: 2021-07-06T01:04:29-04:00
      org.opencontainers.image.description: "[Librespeed](https://github.com/librespeed/speedtest)\
        \ is a very lightweight Speedtest implemented in Javascript, using XMLHttpRequest\
        \ and Web Workers.  No Flash, No Java, No Websocket, No Bullshit."
      org.opencontainers.image.documentation: https://docs.linuxserver.io/images/docker-librespeed
      org.opencontainers.image.licenses: GPL-3.0-only
      org.opencontainers.image.ref.name: 1d3163c6fcb4c4c50bee829ba386fd50533059ad
      org.opencontainers.image.revision: 1d3163c6fcb4c4c50bee829ba386fd50533059ad
      org.opencontainers.image.source: https://github.com/linuxserver/docker-librespeed
      org.opencontainers.image.title: Librespeed
      org.opencontainers.image.url: https://github.com/linuxserver/docker-librespeed/packages
      org.opencontainers.image.vendor: linuxserver.io
      org.opencontainers.image.version: 5.2.4-ls64
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:02
    ports:
      - 86:80/tcp
    restart: unless-stopped
    volumes:
      - /home/nial/speedtest/config:/config:rw
  netdata:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
      - SYS_PTRACE
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    container_name: netdata
    entrypoint:
      - /usr/sbin/run.sh
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DOCKER_GRP=netdata
      - DOCKER_USR=root
      - NETDATA_LISTENER_PORT=19999
    hostname: d2ac8dee5f41
    image: netdata/netdata:latest
    ipc: private
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:03
    ports:
      - 19999:19999/tcp
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - /sys:/host/sys:ro
      - netdatacache:/var/cache/netdata
      - netdatalib:/var/lib/netdata
      - netdataconfig:/etc/netdata
      - /etc/group:/host/etc/group:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /proc:/host/proc:ro
  portainer:
    container_name: portainer
    entrypoint:
      - /portainer
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    hostname: 1558c1bc2843
    image: portainer/portainer-ce
    ipc: private
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:04
    ports:
      - 8000:8000/tcp
      - 9000:9000/tcp
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    working_dir: /
  prometheus:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    command:
      - '--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
        --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles'
    container_name: prometheus
    entrypoint:
      - /bin/prometheus
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    hostname: prometheus
    image: prom/prometheus:latest
    ipc: private
    labels:
      maintainer: 'The Prometheus Authors <prometheus-developers@googlegroups.com>'
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:07
    ports:
      - 9090:9090/tcp
    stdin_open: true
    tty: true
    user: nobody
    volumes:
      - /home/nial/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - e08ecfdb823813a3394245fe77242202f58a6b879e7ef1b50bdbf4851af487b9:/prometheus
    working_dir: /prometheus
  zabbix-agent:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    command:
      - '/usr/sbin/zabbix_agentd --foreground -c /etc/zabbix/zabbix_agentd.conf'
    container_name: zabbix-agent
    entrypoint:
      - /sbin/tini
      - --
      - /usr/bin/docker-entrypoint.sh
    environment:
      - ZBX_SERVER_HOST=192.168.68.125
      - ZBX_HOSTNAME=odroid
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TERM=xterm
      - ZBX_VERSION=5.4.2
      - ZBX_SOURCES=https://git.zabbix.com/scm/zbx/zabbix.git
    hostname: zabbix-agent
    image: zabbix/zabbix-agent:latest
    ipc: private
    labels:
      org.opencontainers.image.authors: 'Alexey Pustovalov <alexey.pustovalov@zabbix.com>'
      org.opencontainers.image.description: 'Zabbix agent is deployed on a monitoring
        target to actively monitor local resources and applications'
      org.opencontainers.image.documentation: https://www.zabbix.com/documentation/5.4/manual/installation/containers
      org.opencontainers.image.licenses: 'GPL v2.0'
      org.opencontainers.image.source: https://git.zabbix.com/scm/zbx/zabbix.git
      org.opencontainers.image.title: 'Zabbix agent'
      org.opencontainers.image.url: https://zabbix.com/
      org.opencontainers.image.vendor: 'Zabbix LLC'
      org.opencontainers.image.version: 5.4.2
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:06
    ports:
      - 10050:10050/tcp
    user: 1997
    working_dir: /var/lib/zabbix
networks:
  host:
    external: true
