version: '3.3'
services:
    prometheus:
        ports:
            - '9090:9090'
        volumes:
            - '/home/nial/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
        image: prom/prometheus
    pihole-exporter:
        environment:
            - PIHOLE_HOSTNAME=t480s
            - PIHOLE_port=8000
            - PORT=9617
        ports:
            - '9617:9617'
        image: 'ekofr/pihole-exporter:latest'
    portainer-ce:
        ports:
            - '8000:8000'
            - '9443:9443'
            - '9000:9000'
        container_name: portainer
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'portainer_data:/data'
        image: 'portainer/portainer-ce:latest'