version: '3.3'
services:
    semaphore:
        ports:
            - 3000:3000
        image: 'semaphoreui/semaphore'
        container_name: semaphore
        environment:
            SEMAPHORE_DB_DIALECT: bolt
            SEMAPHORE_ADMIN_PASSWORD: 2Grangeway
            SEMAPHORE_ADMIN_NAME: admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
            SEMAPHORE_ADMIN: admin
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /home/ubuntu/prowlarr/:/config
        ports:
            - 9696:9696
        restart: unless-stopped
    agent:
        ports:
            - '9001:9001'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/var/lib/docker/volumes:/var/lib/docker/volumes'
        environment:
            - 'true'
        container_name: portainer_agent
        restart: always
        image: 'portainer/agent'
  