version: "3.3"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/ubuntu/prowlarr/:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/ubuntu/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped

  cribl:
    privileged: true
    environment:
      - CRIBL_DIST_MASTER_URL=tcp://criblmaster@100.125.70.69:4200?group=default_fleet&tag=oracle
      - CRIBL_DIST_MODE=managed-edge
      - CRIBL_EDGE=1
    ports:
      - 9420:9420
    volumes:
      - /:/hostfs:ro
    restart: unless-stopped
    container_name: cribl-edge
    image: cribl/cribl:latest

  agent:
    ports:
      - 9001:9001
    container_name: portainer_agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    image: portainer/agent:2.19.4
