version: '3.3'
services:
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /home/ubuntu/prowlarr/:/config
        ports:
            - 9696:9696
        restart: unless-stopped