version: '3.3'
services:
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /home/ubuntu/prowlarr/:/config
        ports:
            - 9696:9696
        restart: unless-stopped
    
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /home/ubuntu/uptime-kuma/data:/app/data
        ports:
            - 3001:3001
        restart: unless-stopped