version: '3.3'
services:
    ssh-log-to-influx:
        environment:
            - INFLUX_HOST=100.127.172.18
            - INFLUX_DB=geossh
        ports:
            - '7070:7070'
        image: acouvreur/ssh-log-to-influx
        restart: unless-stopped
    app:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:

        - '80:80' # Public HTTP Port
        - '443:443' # Public HTTPS Port
        - '81:81' # Admin Web Port
        volumes:
        - /home/nial/nginx-proxy-manager:/data
        - /home/nial/letsencrypt:/etc/letsencrypt
        container_name: nginx-proxy-manager
    goaccess:
        image: 'xavierh/goaccess-for-nginxproxymanager:latest'
        container_name: goaccess
        restart: always
        ports:
            - '7880:7880'
        environment:
            - TZ=Europe/London         
            - LOG_TYPE=NPM
        volumes:
        - /home/nial//nginx-proxy-manager/logs:/opt/log