version: '3.3'
services:
    ssh-log-to-influx:
        environment:
            - INFLUX_HOST=100.127.172.18
            - INFLUX_DB=geossh
        ports:
            - '7070:7070'
        image: acouvreur/ssh-log-to-influx
        restart: unless-stopped
