version: '3.3'
services:
    ssh-log-to-influx:
        environment:
            - INFLUX_HOST=100.127.172.18
            - INFLUX_DB=geossh
        ports:
            - '7070:7070'
        image: acouvreur/ssh-log-to-influx
    agent:
        ports:
            - '9001:9001'
        container_name: portainer_agent
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/var/lib/docker/volumes:/var/lib/docker/volumes'
        image: 'portainer/agent:2.9.3'

    app:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:

        - '80:80' # Public HTTP Port
        - '443:443' # Public HTTPS Port
        - '81:81' # Admin Web Port
        volumes:
        - /users/nial/nginx-proxy-manager:/data
        - /users/nial/letsencrypt:/etc/letsencrypt
