version: '3'

services:
    overseerr:
        image: sctx/overseerr:latest
        container_name: overseerr
        environment:
            - LOG_LEVEL=debug
            - TZ=Europe/London
        ports:
            - 5055:5055
        volumes:
            - /home/nial/overseerr/config:/app/config
        restart: unless-stopped
    qbittorrent-exporter:
        container_name: qbittorrent-exporter
        environment:
            - 'QBITTORRENT_BASE_URL=http://100.102.104.69:8080'
        ports:
            - '17871:17871'
        image: 'caseyscarborough/qbittorrent-exporter:latest'
        restart: unless-stopped