version: '3.3'
services:
    influxdb:
        ports:
            - '8086:8086'
        volumes:
            - '/home/nial/influxdb:/var/lib/influxdb'
        image: 'influxdb:1.8'
        container_name: influxdb
        restart: unless-stopped
    speedtest-to-influxdb:
        container_name: speedflux
        environment:
            - NAMESPACE=None
            - INFLUX_DB_ADDRESS=100.127.172.18
            - INFLUX_DB_PORT=8086
            - INFLUX_DB_USER=root
            - INFLUX_DB_PASSWORD=ad
            - INFLUX_DB_DATABASE=speedtest
            - SPEEDTEST_INTERVAL=5
            - SPEEDTEST_FAIL_INTERVAL=5
            - INFLUX_DB_TAGS=*
            - SPEEDTEST_SERVER_ID=12746
            - LOG_TYPE=info
        image: breadlysm/speedtest-to-influxdb
        restart: unless-stopped
    code-server:
        image: lscr.io/linuxserver/code-server:latest
        container_name: code-server
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - PASSWORD=2Grangeway #optional
          - HASHED_PASSWORD= #optional
          - SUDO_PASSWORD=ad #optional
          - SUDO_PASSWORD_HASH= #optional
          - PROXY_DOMAIN=vscode.n1al.ml #optional
          - DEFAULT_WORKSPACE=/config/workspace #optional
        volumes:
          - /home/nial/code-server/config:/config
        ports:
          - 8443:8443
        restart: unless-stopped