version: '3.3'
services:
    influxdb:
        ports:
            - '8086:8086'
        volumes:
            - '/home/nial/influxdb:/var/lib/influxdb'
        image: 'influxdb:1.8'
        container_name: influxdb
        restart: unless-stopped
    speedtest-to-influxdb:
        container_name: speedflux
        environment:
            - NAMESPACE=None
            - INFLUX_DB_ADDRESS=100.127.172.18
            - INFLUX_DB_PORT=8086
            - INFLUX_DB_USER=root
            - INFLUX_DB_PASSWORD=ad
            - INFLUX_DB_DATABASE=speedtest
            - SPEEDTEST_INTERVAL=5
            - SPEEDTEST_FAIL_INTERVAL=5
            - INFLUX_DB_TAGS=*
            - SPEEDTEST_SERVER_ID=12746
            - LOG_TYPE=info
        image: breadlysm/speedtest-to-influxdb
        restart: unless-stopped
    code-server:
        image: lscr.io/linuxserver/code-server:latest
        container_name: code-server
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - PASSWORD=2Grangeway #optional
          - HASHED_PASSWORD= #optional
          - SUDO_PASSWORD=ad #optional
          - SUDO_PASSWORD_HASH= #optional
          - PROXY_DOMAIN=vscode.n1al.com #optional
          - DEFAULT_WORKSPACE=/config/workspace #optional
        volumes:
          - /home/nial/code-server/config:/config
        ports:
          - 8443:8443
        restart: unless-stopped
    overseerr:
        image: sctx/overseerr:latest
        container_name: overseerr
        environment:
            - LOG_LEVEL=debug
            - TZ=Europe/London
        ports:
            - 5055:5055
        volumes:
            - /home/nial/overseerr/config:/app/config
        restart: unless-stopped
    qbittorrent-exporter:
        container_name: qbittorrent-exporter
        environment:
            - 'QBITTORRENT_BASE_URL=http://100.102.104.69:8080'
        ports:
            - '17871:17871'
        image: 'caseyscarborough/qbittorrent-exporter:latest'
        restart: unless-stopped
    nginx-proxy-manager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:

        - '80:80' # Public HTTP Port
        - '443:443' # Public HTTPS Port
        - '81:81' # Admin Web Port
        volumes:
        - /home/nial/nginx-proxy-manager:/data
        - /home/nial/letsencrypt:/etc/letsencrypt
        container_name: nginx-proxy-manager
    freshrss:
        image: linuxserver/freshrss
        container_name: freshrss
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - /home/nial/freshrss/config:/config
        ports:
            - 8081:80
        restart: unless-stopped
    homebridge:
        image: oznu/homebridge:latest
        restart: always
        network_mode: host
        volumes:
        - ./volumes/homebridge:/homebridge
        logging:
            driver: json-file
            options:
                max-size: "10mb"
                max-file: "1"