name: Deploy Docker Compose newnewtitanium

on:
  push:
    paths:
      - "newnewtitanium/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy to remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NEWNEWTITANIUM_IP }}
          username: ${{ secrets.NEWNEWTITANIUM_USER }}
          password: ${{ secrets.NEWNEWTITANIUM_PASS }}
          script: |
            cd /home/nial/homelab/newnewtitanium
            git pull
            docker compose pull
            docker compose up -d --remove-orphans
