name: Deploy Docker Compose newnewtitanium

on:
  push:
    paths:
      - 'newnewtitanium/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f ./newnewtitanium/docker-compose.yml config

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy to remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NEWNEWTITANIUM_IP }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_KEY }}
          script: |
            cd /home/ubuntu/homelab/oracle
            git pull
            docker compose pull
            docker compose up -d --remove-orphans