name: Deploy Docker Compose pi4

on:
  push:
    paths:
      - 'pi4/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy to remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI4_IP }}
          username: ${{ secrets.PI4_USER }}
          password: ${{ secrets.PI4_PASS }}
          script: |
            cd /home/nial/homelab/pi4
            git pull
            docker compose pull
            docker compose up -d --remove-orphans
